# Generated by Django 5.0.4 on 2024-04-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='name',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
