# Generated by Django 5.0.4 on 2024-04-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_gameroom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
