# Generated by Django 5.0.4 on 2024-04-13 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_player_is_turn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playermove',
            old_name='col',
            new_name='pos',
        ),
        migrations.RemoveField(
            model_name='playermove',
            name='row',
        ),
    ]
